/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AchievementCard: typeof import('./src/components/AchievementCard.vue')['default']
    AudioVisualizer: typeof import('./src/components/AudioVisualizer.vue')['default']
    DifficultyFilter: typeof import('./src/components/DifficultyFilter.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    OnboardingCard: typeof import('./src/components/OnboardingCard.vue')['default']
    PhonemeGrid: typeof import('./src/components/PhonemeGrid.vue')['default']
    PracticeCard: typeof import('./src/components/PracticeCard.vue')['default']
    PracticePopup: typeof import('./src/components/PracticePopup.vue')['default']
    RecordButton: typeof import('./src/components/RecordButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreBreakdown: typeof import('./src/components/ScoreBreakdown.vue')['default']
    ScoreCircle: typeof import('./src/components/ScoreCircle.vue')['default']
    StatsGrid: typeof import('./src/components/StatsGrid.vue')['default']
    StreakCard: typeof import('./src/components/StreakCard.vue')['default']
    VanBadge: typeof import('vant/es')['Badge']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCircle: typeof import('vant/es')['Circle']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanProgress: typeof import('vant/es')['Progress']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTag: typeof import('vant/es')['Tag']
  }
}
